import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import '../firebase_options.dart';

/// Use DefaultFirebaseOptions for explicit Firebase init (generated by FlutterFire CLI).
final FirebaseOptions? kFirebaseOptions = DefaultFirebaseOptions.currentPlatform;

// ── Background message handler (top-level function — required by FlutterFire) ─

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Android only: FCM is delivered to TwilioFcmService (native SDK service)
  // BEFORE this Dart handler runs. This just inits Firebase to satisfy FlutterFire.
  // iOS uses PushKit/CallKit — Twilio voice calls never arrive here on iOS.
  await Firebase.initializeApp(options: kFirebaseOptions);
}

/// Service that manages:
/// - Firebase / FCM initialisation
/// - Notification permission request
/// - Local "Incoming Call" notifications (Android only — iOS uses CallKit)
class NotificationService {
  NotificationService._();
  static final instance = NotificationService._();

  final _fcmTokenController = StreamController<String>.broadcast();
  final _incomingCallController =
      StreamController<Map<String, dynamic>>.broadcast();

  Stream<String> get onFcmToken => _fcmTokenController.stream;
  Stream<Map<String, dynamic>> get onIncomingCall =>
      _incomingCallController.stream;

  final _localNotifications = FlutterLocalNotificationsPlugin();

  static const _channelId = 'twilio_voice_calls';
  static const _channelName = 'Incoming Calls';

  bool _initialised = false;
  String? _fcmToken;

  String? get currentFcmToken => _fcmToken;

  Future<void> initialise() async {
    if (_initialised) return;
    _initialised = true;

    await Firebase.initializeApp(options: kFirebaseOptions);
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    await _requestPermission();
    await _initLocalNotifications();
    await _fetchAndEmitToken();

    FirebaseMessaging.instance.onTokenRefresh.listen((token) {
      _fcmToken = token;
      _fcmTokenController.add(token);
    });

    // Android only: handle foreground FCM Twilio messages.
    // On iOS, incoming calls arrive via PushKit → CallKit (handled in SDK Swift layer).
    if (defaultTargetPlatform == TargetPlatform.android) {
      FirebaseMessaging.onMessage.listen(_handleForegroundMessage);
      FirebaseMessaging.onMessageOpenedApp.listen(_handleNotificationTap);
      final initial = await FirebaseMessaging.instance.getInitialMessage();
      if (initial != null) _handleNotificationTap(initial);
    }
  }

  Future<void> _requestPermission() async {
    final settings = await FirebaseMessaging.instance.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
    debugPrint('[NotificationService] FCM permission: ${settings.authorizationStatus}');
  }

  Future<void> _initLocalNotifications() async {
    const androidSettings = AndroidInitializationSettings('@mipmap/ic_launcher');
    const iosSettings = DarwinInitializationSettings(
      requestAlertPermission: false, // iOS uses CallKit for calls — no local notifications needed
      requestBadgePermission: false,
      requestSoundPermission: false,
    );
    const initSettings = InitializationSettings(
      android: androidSettings,
      iOS: iosSettings,
    );
    await _localNotifications.initialize(
      initSettings,
      onDidReceiveNotificationResponse: _onLocalNotificationTap,
    );

    // Android only: create the notification channel
    await _localNotifications
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(const AndroidNotificationChannel(
          _channelId,
          _channelName,
          description: 'Twilio Voice incoming call notifications',
          importance: Importance.max,
          playSound: true,
          enableVibration: true,
        ));
  }

  void _onLocalNotificationTap(NotificationResponse response) {
    final payload = response.payload;
    if (payload != null) {
      _incomingCallController.add({'callSid': payload, 'source': 'notification_tap'});
    }
  }

  Future<void> _fetchAndEmitToken() async {
    try {
      final token = await FirebaseMessaging.instance
          .getToken()
          .timeout(const Duration(seconds: 10));
      if (token != null) {
        _fcmToken = token;
        _fcmTokenController.add(token);
        debugPrint('[NotificationService] FCM token: ${token.substring(0, 20)}…');
      }
    } catch (e) {
      debugPrint('[NotificationService] ⚠️  Could not get FCM token: $e\n'
          '  Fix: Add SHA-1 to Firebase Console → Project Settings → Your App\n'
          '  Note: On iOS, Twilio uses APNs VoIP (PushKit) — FCM token is not used for voice calls.');
    }
  }

  Future<void> _handleForegroundMessage(RemoteMessage message) async {
    // Android only — iOS calls come via PushKit, not FCM
    final data = message.data;
    final isTwilioVoice = data.containsKey('twi_message_type') &&
        data['twi_message_type'] == 'twilio.voice.call';

    if (isTwilioVoice) {
      _incomingCallController.add({
        'callSid': data['twi_call_sid'] ?? '',
        'from': data['twi_from'] ?? 'Unknown',
        'source': 'foreground_fcm',
        'raw': data,
      });

      await _showIncomingCallNotification(
        callSid: data['twi_call_sid'] ?? '',
        from: (data['twi_from'] ?? 'Unknown')
            .toString()
            .replaceFirst('client:', ''),
      );
    }
  }

  void _handleNotificationTap(RemoteMessage message) {
    final data = message.data;
    if (data.containsKey('twi_call_sid')) {
      _incomingCallController.add({
        'callSid': data['twi_call_sid'] ?? '',
        'from': data['twi_from'] ?? 'Unknown',
        'source': 'notification_tap',
        'raw': data,
      });
    }
  }

  Future<void> _showIncomingCallNotification({
    required String callSid,
    required String from,
  }) async {
    // Android only — iOS uses CallKit which shows its own system UI
    if (defaultTargetPlatform != TargetPlatform.android) return;

    const androidDetails = AndroidNotificationDetails(
      _channelId,
      _channelName,
      channelDescription: 'Twilio Voice incoming call notifications',
      importance: Importance.max,
      priority: Priority.max,
      category: AndroidNotificationCategory.call,
      fullScreenIntent: true,
      ongoing: true,
      autoCancel: false,
      icon: '@mipmap/ic_launcher',
    );
    const details = NotificationDetails(android: androidDetails);

    await _localNotifications.show(
      1001,
      'Incoming Call',
      '$from is calling…',
      details,
      payload: callSid,
    );
  }

  Future<void> dismissIncomingCallNotification() async {
    await _localNotifications.cancel(1001);
  }

  void dispose() {
    _fcmTokenController.close();
    _incomingCallController.close();
  }
}

