// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6VAStyOEWJjw_8R1olna42DTqEz67pqU',
    appId: '1:393075605850:web:eb97c74db3cef09cac7363',
    messagingSenderId: '393075605850',
    projectId: 'multipleappsupport',
    authDomain: 'multipleappsupport.firebaseapp.com',
    storageBucket: 'multipleappsupport.appspot.com',
    measurementId: 'G-F8G4S3XNRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI6vW0E-36kuWr4kZtLxVju3zu881t_wE',
    appId: '1:393075605850:android:43d0bc61d60eba67ac7363',
    messagingSenderId: '393075605850',
    projectId: 'multipleappsupport',
    storageBucket: 'multipleappsupport.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_bV_4KKCrJDLagf_hAJAFiqMazEzPeg',
    appId: '1:393075605850:ios:ff269837568a838aac7363',
    messagingSenderId: '393075605850',
    projectId: 'multipleappsupport',
    storageBucket: 'multipleappsupport.appspot.com',
    iosBundleId: 'com.example.minimalExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_bV_4KKCrJDLagf_hAJAFiqMazEzPeg',
    appId: '1:393075605850:ios:ff269837568a838aac7363',
    messagingSenderId: '393075605850',
    projectId: 'multipleappsupport',
    storageBucket: 'multipleappsupport.appspot.com',
    iosBundleId: 'com.example.minimalExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6VAStyOEWJjw_8R1olna42DTqEz67pqU',
    appId: '1:393075605850:web:7c8cde4656bfc705ac7363',
    messagingSenderId: '393075605850',
    projectId: 'multipleappsupport',
    authDomain: 'multipleappsupport.firebaseapp.com',
    storageBucket: 'multipleappsupport.appspot.com',
    measurementId: 'G-RTDFC1YBHZ',
  );
}
